### ISSUE TITLE
Navigation Bar is hidden/ disappears

### ISSUE THREAD

**Issue by wengkeong94** [recruit-mp/RMPZoomTransitionAnimator#24]
From the demo project, I clicked into "CollectionView, Navigation Push Transition", then clicked one of the cells in the ViewController and lastly when i clicked "back"  from DetailViewController (Result: navigation bar is hidden). This happens to my project as well when i implemented this. Please help.

**Comment by vivekjains** [comment]
I'm also having the same issue.

**Comment by wengkeong94** [comment]
@vivekjains i solved it by replacing this. 
`animator.goingForward = (operation == UINavigationControllerOperationPush || operation == UINavigationControllerOperationPop);`
