### ISSUE TITLE
iPad Example

### ISSUE THREAD

**Issue by JARMourato** [recruit-mp/RMPZoomTransitionAnimator#3]
Can you please add an iPad example? i seem to be unable to make it work on the iPad, for some reason.

**Comment by mpon** [comment]
If i have time, i will try.  Thanks!

**Comment by yhirano** [comment]
+1

**Comment by mpon** [comment]
@JARMourato I added an iPad example #5. Please try it.

**Comment by JARMourato** [comment]
Exactly what i needed. Thanks :)

**Comment by mpon** [comment]
thank you for checking. :smile:
