### ISSUE TITLE
[Enhancement] Callback on animation completions

### ISSUE THREAD

**Issue by jfradj** [recruit-mp/RMPZoomTransitionAnimator#4]
Hello,

It would be great to have two optionals methods in RMPZoomTransitionAnimating protocol to be notified of the end of the forward and backward animations.

Great work by the way.

Cheers

**Comment by jfradj** [comment]
Or even better, the RMPZoomTransitionAnimating protocol could require a new method to get the original UIImageView (the source of the image view returned by -(UIImageView *)transitionSourceImageView; ) and hide it, while the copy is being animated. And when the animation is done, the original could be shown.

That will prevent the original views to be shown while animating.

Hope it's clear.

**Comment by mpon** [comment]
Thanks for the feedback @jfradj. I think this will need some improvement.
I deal with something lightly and temporarily in [RMPZoomTransitionAnimator.m#L59-L62](https://github.com/recruit-mp/RMPZoomTransitionAnimator/blob/master/Pod/Classes/RMPZoomTransitionAnimator.m#L59-L62) to add the alpha view.
So, i will try your suggestion, and hope your pull request!

**Comment by mpon** [comment]
fix #6
